"""API 路由彙總：掛載 users、agents、source_files、prompt_templates、bi_projects 等 endpoint"""
from fastapi import APIRouter
from app.api.endpoints import users, agents, agent_catalog, chat, chat_dev, chat_compute_tool, chat_threads, chat_insights, agent_insights, source_files, prompt_templates, tenants, companies, bi_projects, bi_sources, bi_schemas, bi_sample_qa, llm_configs, activation, km, km_kb, km_connectors, widget_admin, api_keys, public_bot, public_speech, ordering, speech, ocr, bots, widget_bot, doc_refiner

router = APIRouter()
router.include_router(users.router, prefix="/users", tags=["users"])
router.include_router(tenants.router, prefix="/tenants", tags=["tenants"])
router.include_router(agent_catalog.router, prefix="/agent-catalog", tags=["agent-catalog"])
router.include_router(agents.router, prefix="/agents", tags=["agents"])
router.include_router(chat.router, prefix="/chat", tags=["chat"])
router.include_router(chat_threads.router, prefix="/chat", tags=["chat-threads"])
router.include_router(chat_insights.router, prefix="/chat/insights", tags=["chat-insights"])
router.include_router(agent_insights.router, prefix="/agent-insights", tags=["agent-insights"])
router.include_router(chat_dev.router, prefix="/chat/dev", tags=["chat-dev"])
router.include_router(chat_compute_tool.router, prefix="/chat", tags=["chat-compute-tool"])
router.include_router(source_files.router, prefix="/source-files", tags=["source-files"])
router.include_router(prompt_templates.router, prefix="/prompt-templates", tags=["prompt-templates"])
router.include_router(companies.router, prefix="/companies", tags=["companies"])
router.include_router(bi_projects.router, prefix="/bi-projects", tags=["bi-projects"])
router.include_router(bi_sources.router, prefix="/bi-sources", tags=["bi-sources"])
router.include_router(bi_schemas.router, prefix="/bi-schemas", tags=["bi-schemas"])
router.include_router(bi_sample_qa.router, prefix="/bi-sample-qa", tags=["bi-sample-qa"])
router.include_router(llm_configs.router, prefix="/llm-configs", tags=["llm-configs"])
router.include_router(activation.router, prefix="/activate", tags=["activation"])
router.include_router(km.router, prefix="/km", tags=["km"])
router.include_router(km_kb.router, prefix="/km", tags=["km-kb"])
router.include_router(km_connectors.router, prefix="/km", tags=["km-connectors"])
router.include_router(widget_admin.router, prefix="/widget-admin", tags=["widget-admin"])
router.include_router(api_keys.router, prefix="/api-keys", tags=["api-keys"])
router.include_router(public_bot.router, prefix="/public/bot", tags=["public-bot"])
router.include_router(public_speech.router, prefix="/public/speech", tags=["public-speech"])
router.include_router(ordering.router, prefix="/public/ordering", tags=["ordering"])
router.include_router(speech.router, prefix="/speech", tags=["speech"])
router.include_router(ocr.router, prefix="/ocr", tags=["ocr"])
router.include_router(bots.router, prefix="/bots", tags=["bots"])
router.include_router(widget_bot.router, prefix="/widget/bot", tags=["widget-bot"])
router.include_router(doc_refiner.router, prefix="/doc-refiner", tags=["doc-refiner"])
